import React, { createContext, useContext, useState, ReactNode } from "react";

export type Language = "ja" | "vi";

const translations = {
  ja: {
    // Header
    header: {
      search: "レストラン検索",
      messages: "メッセージ",
      storeManagement: "店舗管理",
      login: "ログイン",
      signup: "新規登録",
      profileSettings: "プロフィール設定",
      logout: "ログアウト",
    },
    // Home
    home: {
      badge: "ハノイで一番信頼できるベトナム料理ガイド",
      subtitle: "近い店 — ハノイの美食を探そう",
      description: "ハノイで日本語対応のベトナム料理レストランを簡単に見つけられるアプリ",
      searchPlaceholder: "レストラン名、料理名で検索... (例: フォー、ブンチャー)",
      searchBtn: "検索",
      city: "ハノイ",
      quickSuggestions: [
        { label: "近くのお店", icon: "📍", filter: "near" },
        { label: "日本人好み", icon: "🍜", filter: "popular" },
        { label: "今営業中", icon: "🟢", filter: "open" },
        { label: "リーズナブル", icon: "💰", filter: "cheap" },
      ],
      stats: [
        { value: "120+", label: "レストラン" },
        { value: "1,500+", label: "レビュー" },
        { value: "98%", label: "日本語対応" },
      ],
      mapTitle: "地図で探す",
      mapSub: "Tìm kiếm trên bản đồ",
      viewAll: "すべて見る",
      viewMap: "地図で全部見る",
      quickAccess: "クイックアクセス",
      foodItems: [
        { icon: "🍜", label: "フォー", sub: "Phở", filter: "Phở" },
        { icon: "🥢", label: "ブンチャー", sub: "Bún chả", filter: "Bún chả" },
        { icon: "🥖", label: "バインミー", sub: "Bánh mì", filter: "Bánh mì" },
        { icon: "🌿", label: "ゴイクォン", sub: "Gỏi cuốn", filter: "Gỏi cuốn" },
        { icon: "🐟", label: "チャーカー", sub: "Chả cá", filter: "Chả cá" },
      ],
      featuredTitle: "⭐ 人気レストラン",
      featuredSub: "Nhà hàng được yêu thích nhất",
      nearbyTitle: "📍 近くのお店",
      nearbySub: "Quán ăn gần bạn nhất",
      viewMore: "もっと見る",
      ctaTitle: "レビューを書いてコミュニティに貢献しよう",
      ctaDesc: "アカウントを作成してレビューを投稿し、レストランのオーナーと直接チャットできます。",
      ctaSignup: "無料で登録する",
      ctaLogin: "ログイン",
      footerDesc: "ハノイで日本語対応のベトナム料理レストランを見つけるためのアプリ",
      footerMenu: "メニュー",
      footerContact: "お問い合わせ",
      footerCity: "ハノイ、ベトナム",
      footerSearch: "レストラン検索",
      footerLogin: "ログイン",
      footerSignup: "新規登録",
    },
    // Search
    search: {
      placeholder: "レストラン名、料理で検索...",
      filter: "フィルター",
      list: "リスト",
      map: "地図",
      foodType: "料理の種類",
      priceRange: "価格帯",
      distance: "距離",
      other: "その他",
      openOnly: "今営業中のみ",
      minRating: "最低評価",
      clearFilters: "フィルターをクリア",
      results: "件のレストランが見つかりました",
      noResults: "検索結果が見つかりません",
      noResultsDesc: "フィルターを変更して再度お試しください",
      detailLink: "詳細を見る →",
      hanoiCenter: "ハノイ中心部",
      priceRanges: [
        { label: "〜50,000đ" },
        { label: "50k〜100k" },
        { label: "100k〜200k" },
        { label: "200k以上" },
      ],
      distanceRanges: [
        { label: "500m以内" },
        { label: "1km以内" },
        { label: "2km以内" },
        { label: "5km以内" },
      ],
    },
    // Restaurant Detail
    detail: {
      back: "戻る",
      open: "🟢 営業中",
      closed: "🔴 閉店",
      directions: "道順を調べる",
      askOwner: "オーナーに聞く",
      askOwnerLogin: "オーナーに聞く（ログイン必要）",
      writeReview: "レビューを書く",
      tabInfo: "📋 情報",
      tabReviews: "⭐ レビュー",
      aboutTitle: "お店について",
      galleryTitle: "フォトギャラリー",
      menuTitle: "🍽 メニュー",
      basicInfo: "基本情報",
      priceRange: "価格帯",
      avgPrice: "平均",
      perPerson: "/人",
      foodTags: "料理タグ",
      japaneseSupport: "日本語対応",
      japaneseSupportDesc: "このお店は日本語で対応しています",
      reviews: "件のレビュー",
      reviewsCta: "レビューを書く",
      reviewsCtaDesc: "あなたの体験を共有してください",
      noReviews: "まだレビューがありません",
      noReviewsFirst: "最初のレビューを書いてください！",
      noMatchingReviews: "条件に合うレビューがありません",
      helpfulQuestion: "このレビューは役に立ちましたか？",
      filterRating: "評価で絞り込み",
      sortReviews: "並び替え",
      allStars: "すべて",
      sortHelpful: "参考度",
      sortNewest: "新しい順",
      sortOldest: "古い順",
      yourReview: "あなたのレビュー",
      qrTitle: "QRコード・リンク共有",
      qrScanDesc: "QRコードをスキャンしてこのページを共有",
      copy: "コピー",
      copied: "コピー済み！",
      close: "閉じる",
    },
    // Login
    login: {
      title: "ログイン",
      welcome: "ChikaiMiseへようこそ",
      email: "メールアドレス",
      password: "パスワード",
      passwordPlaceholder: "パスワードを入力",
      forgotPassword: "パスワードを忘れた方はこちら",
      loginBtn: "ログイン",
      loggingIn: "ログイン中...",
      noAccount: "アカウントをお持ちでない方は",
      signupLink: "新規登録",
      demoTitle: "デモアカウントで試す",
      demoNote: "※ 任意のパスワードでログインできます",
      dinerLabel: "お客さん",
      ownerLabel: "オーナー",
      errorRequired: "メールアドレスとパスワードを入力してください",
      errorInvalid: "メールアドレスまたはパスワードが正しくありません",
    },
    // Forgot Password
    forgotPassword: {
      title: "パスワードをリセット",
      subtitle: "登録したメールアドレスにリセットリンクを送信します",
      email: "メールアドレス",
      emailPlaceholder: "example@email.com",
      sendBtn: "リセットリンクを送信",
      sending: "送信中...",
      backToLogin: "ログインに戻る",
      successTitle: "リクエストを受け付けました",
      successDesc: "アカウントが存在する場合、パスワードリセット用のリンクをメールで送信します。",
      successNote: "※ メールが届かない場合は、迷惑メールフォルダもご確認ください。",
      backBtn: "ログインページに戻る",
      errorRequired: "メールアドレスを入力してください",
      errorInvalid: "有効なメールアドレスを入力してください",
      errorNotFound: "このメールアドレスは登録されていません",
    },
    // Signup
    signup: {
      title: "新規登録",
      welcome: "ChikaiMiseへようこそ！アカウントを作成しましょう",
      accountType: "アカウントの種類",
      dinerRole: "グルメ探し",
      dinerSub: "お客さん",
      ownerRole: "店舗オーナー",
      ownerSub: "飲食店主",
      name: "お名前 / Tên hiển thị",
      namePlaceholder: "田中 太郎 / Nguyễn Văn An",
      email: "メールアドレス",
      password: "パスワード",
      passwordPlaceholder: "6文字以上",
      passwordStrength: "強度:",
      confirmPassword: "パスワード確認",
      confirmPlaceholder: "パスワードを再入力",
      createBtn: "アカウントを作成",
      creating: "登録中...",
      haveAccount: "すでにアカウントをお持ちの方は",
      loginLink: "ログイン",
      strengthWeak: "弱い",
      strengthNormal: "普通",
      strengthGood: "まあまあ",
      strengthStrong: "強い",
      errorName: "お名前を入力してください",
      errorEmail: "メールアドレスを入力してください",
      errorEmailInvalid: "有効なメールアドレスを入力してください",
      errorPasswordShort: "パスワードは6文字以上で入力してください",
      errorPasswordMismatch: "パスワードが一致しません",
      errorEmailExists: "このメールアドレスはすでに登録されています",
      successAlert: "アカウントが作成されました！ログイン画面に移動します...",
    },
    // Chat
    chat: {
      title: "メッセージ",
      searchPlaceholder: "会話を検索...",
      online: "オンライン",
      messagePlaceholder: "メッセージを入力...",
      findRestaurant: "レストランを探してチャット",
      selectConv: "会話を選択してください",
      selectDesc: "左のリストから会話を選ぶか、レストランのページからチャットを開始してください。",
      findRestaurantBtn: "レストランを探す",
      detailLink: "詳細 →",
      customerLabel: "お客さま",
      restaurantLabel: "お店",
      sent: "送信済み",
      read: "既読",
      loading: "読み込み中...",
      emptyTitle: "まだ会話がありません",
      emptyDesc: "レストラン詳細ページからお店にメッセージを送れます。",
      noMessages: "まだメッセージがありません",
    },
    // Profile
    profile: {
      editProfile: "プロフィール編集",
      changePassword: "パスワード変更",
      basicInfoTitle: "基本情報を編集",
      name: "お名前 / Tên hiển thị",
      email: "メールアドレス",
      phone: "電話番号",
      address: "住所 / Địa chỉ tại Hà Nội",
      addressPlaceholder: "例: Hoàn Kiếm, Hà Nội",
      saveBtn: "保存する",
      saved: "保存しました！",
      passwordTitle: "パスワード変更",
      currentPassword: "現在のパスワード",
      newPassword: "新しいパスワード",
      newPasswordPlaceholder: "6文字以上",
      confirmPassword: "新しいパスワード（確認）",
      confirmPlaceholder: "もう一度入力",
      changePasswordBtn: "パスワードを変更する",
      storeManagement: "店舗管理",
      ownerRole: "店舗オーナー 🏪",
      dinerRole: "グルメ探し 🍜",
      passwordMismatch: "新しいパスワードが一致しません",
    },
    // Write Review
    review: {
      back: "戻る",
      title: "レビューを書く",
      ratingTitle: "総合評価",
      ratingDesc: "このレストランを5段階で評価してください",
      commentTitle: "コメント",
      commentJpNote: "日本語でコメントをお書きください",
      commentPlaceholder: "例：スープの深みが素晴らしく、とても満足しました。スタッフの対応も親切でした。ぜひまた来たいと思います。",
      imageTitle: "写真を追加（任意）",
      imageDesc: "jpg, jpeg, png, webp形式、1枚10MBまで。最大3枚アップロードできます",
      addImage: "追加",
      tipsTitle: "💡 良いレビューのコツ",
      tips: [
        "料理の味・見た目について具体的に書く",
        "スタッフの日本語対応について触れる",
        "価格に対するコスパを評価する",
        "日本人のお口に合うかどうかを伝える",
      ],
      submitBtn: "レビューを投稿する",
      submitting: "投稿中...",
      successTitle: "レビューを投稿しました！",
      successDesc: "ありがとうございます。レストランの詳細に戻ります...",
      loginRequired: "レビューを書くにはログインが必要です",
      notFound: "レストランが見つかりません",
      backToSearch: "検索に戻る",
      ratingLabels: ["", "とても不満", "不満", "普通", "満足", "大変満足！"],
      errorRating: "評価を選択してください",
      errorComment: "コメントを入力してください",
      errorCommentLength: "コメントは20文字以上で入力してください",
      errorImageSize: "各画像は10MB以下にしてください",
      errorImageType: "jpg、jpeg、png、webp形式の画像のみアップロードできます",
      errorImageCount: "画像は最大3枚までアップロードできます",
      submitError: "レビューを投稿できませんでした。もう一度お試しください",
    },
    // Register Store
    registerStore: {
      back: "戻る",
      title: "新規店舗登録",
      pageTitle: "店舗情報を登録",
      pageSub: "お店の情報を入力してください",
      step1: "基本情報",
      step2: "メニュー",
      step3: "写真・タグ",
      nameVn: "店名（ベトナム語）",
      errNameVn: "ベトナム語名を入力してください",
      nameJp: "店名（日本語）",
      errNameJp: "日本語名を入力してください",
      address: "住所 / Địa chỉ",
      errAddress: "住所を入力してください",
      errRequired: "必須項目をすべて入力してください",
      selectMap: "地図から選択",
      phone: "電話番号",
      errPhone: "電話番号を入力してください",
      openHours: "営業時間",
      errOpenHours: "営業時間を入力してください",
      avgPrice: "平均単価 (VND)",
      errAvgPrice: "平均単価を入力してください",
      descVn: "説明（ベトナム語）",
      errDescVn: "ベトナム語の説明を入力してください",
      descVnPh: "お店の説明をベトナム語で...",
      descJp: "説明（日本語）",
      errDescJp: "日本語の説明を入力してください",
      descJpPh: "お店の説明を日本語で...",
      nextStep2: "次へ：メニュー設定",
      menuTitle: "メニュー設定",
      addBtn: "追加",
      menuLabel: "メニュー",
      errMenuRequired: "メニューを1品以上追加してください",
      dishImage: "料理写真",
      addDishImage: "写真を追加",
      errDishImage: "料理写真を追加してください",
      dishNameVn: "料理名（ベトナム語）",
      errDishNameVn: "ベトナム語の料理名を入力してください",
      dishNameJp: "料理名（日本語）",
      errDishNameJp: "日本語の料理名を入力してください",
      price: "価格 (VND)",
      errDishPrice: "価格を1以上で入力してください",
      dishDesc: "説明（任意）",
      errDishDesc: "料理説明を入力してください",
      prevBtn: "前へ",
      nextStep3: "次へ：写真・タグ",
      photoTitle: "店舗・料理写真",
      photoSub: "最大8枚の写真をアップロード",
      addPhoto: "写真を追加",
      errImages: "店舗写真を1枚以上追加してください",
      errorImageCount: "写真は最大8枚までアップロードできます",
      errorImageSize: "各写真は10MB以下にしてください",
      errorImageType: "jpg, jpeg, png, webp形式の写真のみアップロードできます",
      tagTitle: "料理タグ",
      tagSub: "お店の料理に合うタグを選択してください",
      errTags: "料理タグを1つ以上選択してください",
      submitBtn: "店舗を登録する",
      saving: "保存中...",
      successTitle: "店舗を登録しました！",
      successSub: "店舗管理ページに戻ります...",
      errSubmit: "保存できません。もう一度お試しください。",
    },
    // Owner List
    ownerList: {
      title: "私の店舗一覧",
      titleSub: "Danh sách quán ăn của bạn",
      addBtn: "新規登録",
      addBtnMobile: "追加",
      statStores: "登録店舗",
      statReviews: "総レビュー",
      statRating: "平均評価",
      open: "営業中",
      closed: "閉店",
      reviewsCount: "件のレビュー",
      edit: "編集",
      publicPage: "公開ページ",
      messages: "メッセージ",
      emptyTitle: "まだ店舗を登録していません",
      emptyDesc: "最初の店舗を登録して、日本人のお客様に見つけてもらいましょう！",
      emptyBtn: "最初の店舗を登録する",
      addNew: "新しい店舗を登録する",
    },
    // Manage Store
    manageStore: {
      back: "戻る",
      publicPage: "公開ページ →",
      notFound: "店舗が見つかりません",
      open: "営業中",
      closed: "閉店",
      saved: "変更を保存しました！",
      tabs: {
        basic: "基本情報",
        menu: "メニュー",
        photos: "写真・タグ",
      },
      nameVn: "店名（ベトナム語）",
      nameJp: "店名（日本語）",
      address: "住所",
      phone: "電話番号",
      openHours: "営業時間",
      avgPrice: "平均単価 (VND)",
      descVn: "説明（ベトナム語）",
      descJp: "説明（日本語）",
      saveChanges: "変更を保存",
      menuTitle: "メニュー管理",
      add: "追加",
      dishImage: "料理写真",
      addDishImage: "写真を追加",
      changePhoto: "変更",
      dishNameVn: "料理名（ベトナム語）",
      dishNameJp: "料理名（日本語）",
      price: "価格",
      description: "説明",
      saveMenu: "メニューを保存",
      photoTitle: "写真管理",
      addPhoto: "写真を追加",
      tagTitle: "料理タグ",
      savePhotos: "変更を保存",
      errorImageCount: "写真は最大8枚までアップロードできます",
      errorImageSize: "各写真は10MB以下にしてください",
      errorImageType: "jpg, jpeg, png, webp形式の写真のみアップロードできます",
      submitError: "保存できません。もう一度お試しください。",
    },
    // Restaurant Card
    card: {
      open: "営業中",
      closed: "閉店",
      reviews: "件",
      from: "〜",
    },
  },

  vi: {
    // Header
    header: {
      search: "Tìm nhà hàng",
      messages: "Tin nhắn",
      storeManagement: "Quản lý quán",
      login: "Đăng nhập",
      signup: "Đăng ký",
      profileSettings: "Cài đặt hồ sơ",
      logout: "Đăng xuất",
    },
    // Home
    home: {
      badge: "Hướng dẫn ẩm thực Việt Nam đáng tin cậy nhất tại Hà Nội",
      subtitle: "近い店 — Khám phá ẩm thực Hà Nội",
      description: "Ứng dụng giúp người Nhật dễ dàng tìm nhà hàng Việt Nam có chủ nói tiếng Nhật tại Hà Nội",
      searchPlaceholder: "Tìm theo tên nhà hàng, món ăn... (VD: Phở, Bún chả)",
      searchBtn: "Tìm kiếm",
      city: "Hà Nội",
      quickSuggestions: [
        { label: "Gần đây", icon: "📍", filter: "near" },
        { label: "Hợp khẩu vị Nhật", icon: "🍜", filter: "popular" },
        { label: "Đang mở cửa", icon: "🟢", filter: "open" },
        { label: "Giá hợp lý", icon: "💰", filter: "cheap" },
      ],
      stats: [
        { value: "120+", label: "Nhà hàng" },
        { value: "1.500+", label: "Đánh giá" },
        { value: "98%", label: "Hỗ trợ tiếng Nhật" },
      ],
      mapTitle: "Tìm trên bản đồ",
      mapSub: "地図で探す",
      viewAll: "Xem tất cả",
      viewMap: "Xem tất cả trên bản đồ",
      quickAccess: "Truy cập nhanh",
      foodItems: [
        { icon: "🍜", label: "Phở", sub: "フォー", filter: "Phở" },
        { icon: "🥢", label: "Bún chả", sub: "ブンチャー", filter: "Bún chả" },
        { icon: "🥖", label: "Bánh mì", sub: "バインミー", filter: "Bánh mì" },
        { icon: "🌿", label: "Gỏi cuốn", sub: "ゴイクォン", filter: "Gỏi cuốn" },
        { icon: "🐟", label: "Chả cá", sub: "チャーカー", filter: "Chả cá" },
      ],
      featuredTitle: "⭐ Nhà hàng nổi bật",
      featuredSub: "人気レストラン",
      nearbyTitle: "📍 Quán gần bạn",
      nearbySub: "近くのお店",
      viewMore: "Xem thêm",
      ctaTitle: "Chia sẻ trải nghiệm của bạn với cộng đồng",
      ctaDesc: "Tạo tài khoản để đăng đánh giá và nhắn tin trực tiếp với chủ nhà hàng.",
      ctaSignup: "Đăng ký miễn phí",
      ctaLogin: "Đăng nhập",
      footerDesc: "Ứng dụng kết nối người Nhật với nhà hàng Việt Nam có chủ nói tiếng Nhật tại Hà Nội",
      footerMenu: "Menu",
      footerContact: "Liên hệ",
      footerCity: "Hà Nội, Việt Nam",
      footerSearch: "Tìm nhà hàng",
      footerLogin: "Đăng nhập",
      footerSignup: "Đăng ký",
    },
    // Search
    search: {
      placeholder: "Tìm theo tên nhà hàng, món ăn...",
      filter: "Bộ lọc",
      list: "Danh sách",
      map: "Bản đồ",
      foodType: "Loại món ăn",
      priceRange: "Khoảng giá",
      distance: "Khoảng cách",
      other: "Khác",
      openOnly: "Chỉ đang mở cửa",
      minRating: "Đánh giá tối thiểu",
      clearFilters: "Xóa bộ lọc",
      results: "nhà hàng được tìm thấy",
      noResults: "Không tìm thấy kết quả",
      noResultsDesc: "Hãy thay đổi bộ lọc và thử lại",
      detailLink: "Xem chi tiết →",
      hanoiCenter: "Trung tâm Hà Nội",
      priceRanges: [
        { label: "〜50.000đ" },
        { label: "50k〜100k" },
        { label: "100k〜200k" },
        { label: "Trên 200k" },
      ],
      distanceRanges: [
        { label: "Trong 500m" },
        { label: "Trong 1km" },
        { label: "Trong 2km" },
        { label: "Trong 5km" },
      ],
    },
    // Restaurant Detail
    detail: {
      back: "Quay lại",
      open: "🟢 Đang mở",
      closed: "🔴 Đã đóng",
      directions: "Chỉ đường",
      askOwner: "Nhắn tin chủ quán",
      askOwnerLogin: "Nhắn tin chủ quán (cần đăng nhập)",
      writeReview: "Viết đánh giá",
      tabInfo: "📋 Thông tin",
      tabReviews: "⭐ Đánh giá",
      aboutTitle: "Giới thiệu quán",
      galleryTitle: "Thư viện ảnh",
      menuTitle: "🍽 Thực đơn",
      basicInfo: "Thông tin cơ bản",
      priceRange: "Khoảng giá",
      avgPrice: "Trung bình",
      perPerson: "/người",
      foodTags: "Thẻ món ăn",
      japaneseSupport: "Hỗ trợ tiếng Nhật",
      japaneseSupportDesc: "Quán này có chủ nói được tiếng Nhật",
      reviews: "đánh giá",
      reviewsCta: "Viết đánh giá",
      reviewsCtaDesc: "Chia sẻ trải nghiệm của bạn",
      noReviews: "Chưa có đánh giá nào",
      noReviewsFirst: "Hãy là người đầu tiên đánh giá!",
      noMatchingReviews: "Không có đánh giá phù hợp với bộ lọc",
      helpfulQuestion: "Đánh giá này có hữu ích không?",
      filterRating: "Lọc theo sao",
      sortReviews: "Sắp xếp",
      allStars: "Tất cả",
      sortHelpful: "Hữu ích nhất",
      sortNewest: "Mới nhất",
      sortOldest: "Cũ nhất",
      yourReview: "Đánh giá của bạn",
      qrTitle: "Chia sẻ QR Code & Liên kết",
      qrScanDesc: "Quét QR Code để chia sẻ trang này",
      copy: "Sao chép",
      copied: "Đã sao chép!",
      close: "Đóng",
    },
    // Login
    login: {
      title: "Đăng nhập",
      welcome: "Chào mừng đến ChikaiMise",
      email: "Email",
      password: "Mật khẩu",
      passwordPlaceholder: "Nhập mật khẩu",
      forgotPassword: "Quên mật khẩu?",
      loginBtn: "Đăng nhập",
      loggingIn: "Đang đăng nhập...",
      noAccount: "Chưa có tài khoản?",
      signupLink: "Đăng ký",
      demoTitle: "Thử với tài khoản demo",
      demoNote: "※ Có thể đăng nhập với bất kỳ mật khẩu nào",
      dinerLabel: "Khách hàng",
      ownerLabel: "Chủ quán",
      errorRequired: "Vui lòng nhập email và mật khẩu",
      errorInvalid: "Email hoặc mật khẩu không đúng",
    },
    // Forgot Password
    forgotPassword: {
      title: "Reset mật khẩu",
      subtitle: "Gửi liên kết reset mật khẩu đến email đã đăng ký",
      email: "Email",
      emailPlaceholder: "example@email.com",
      sendBtn: "Gửi liên kết reset",
      sending: "Đang gửi...",
      backToLogin: "Quay lại đăng nhập",
      successTitle: "Đã tiếp nhận yêu cầu",
      successDesc: "Nếu email tồn tại trong hệ thống, liên kết reset mật khẩu sẽ được gửi đến địa chỉ đó.",
      successNote: "※ Nếu không thấy email, hãy kiểm tra thư mục spam.",
      backBtn: "Quay lại trang đăng nhập",
      errorRequired: "Vui lòng nhập email",
      errorInvalid: "Email không hợp lệ",
      errorNotFound: "Email này chưa được đăng ký",
    },
    // Signup
    signup: {
      title: "Đăng ký",
      welcome: "Chào mừng đến ChikaiMise! Hãy tạo tài khoản",
      accountType: "Loại tài khoản",
      dinerRole: "Tìm quán ăn",
      dinerSub: "Khách hàng",
      ownerRole: "Chủ nhà hàng",
      ownerSub: "Quản lý quán",
      name: "Tên hiển thị / お名前",
      namePlaceholder: "Nguyễn Văn An / 田中 太郎",
      email: "Email",
      password: "Mật khẩu",
      passwordPlaceholder: "Ít nhất 6 ký tự",
      passwordStrength: "Độ mạnh:",
      confirmPassword: "Xác nhận mật khẩu",
      confirmPlaceholder: "Nhập lại mật khẩu",
      createBtn: "Tạo tài khoản",
      creating: "Đang đăng ký...",
      haveAccount: "Đã có tài khoản?",
      loginLink: "Đăng nhập",
      strengthWeak: "Yếu",
      strengthNormal: "Trung bình",
      strengthGood: "Khá",
      strengthStrong: "Mạnh",
      errorName: "Vui lòng nhập tên",
      errorEmail: "Vui lòng nhập email",
      errorEmailInvalid: "Email không hợp lệ",
      errorPasswordShort: "Mật khẩu phải có ít nhất 6 ký tự",
      errorPasswordMismatch: "Mật khẩu không khớp",
      errorEmailExists: "Email này đã tồn tại, vui lòng nhập lại",
      successAlert: "Đăng ký thành công! Đang chuyển hướng đến trang đăng nhập...",
    },
    // Chat
    chat: {
      title: "Tin nhắn",
      searchPlaceholder: "Tìm kiếm cuộc trò chuyện...",
      online: "Đang online",
      messagePlaceholder: "Nhập tin nhắn...",
      findRestaurant: "Tìm nhà hàng để chat",
      selectConv: "Chọn cuộc trò chuyện",
      selectDesc: "Chọn từ danh sách bên trái hoặc bắt đầu chat từ trang nhà hàng.",
      findRestaurantBtn: "Tìm nhà hàng",
      detailLink: "Chi tiết →",
      customerLabel: "Khách hàng",
      restaurantLabel: "Quán",
      sent: "Đã gửi",
      read: "Đã đọc",
      loading: "Đang tải...",
      emptyTitle: "Chưa có cuộc trò chuyện",
      emptyDesc: "Bạn có thể nhắn cho quán từ trang chi tiết nhà hàng.",
      noMessages: "Chưa có tin nhắn nào",
    },
    // Profile
    profile: {
      editProfile: "Chỉnh sửa hồ sơ",
      changePassword: "Đổi mật khẩu",
      basicInfoTitle: "Chỉnh sửa thông tin cơ bản",
      name: "Tên hiển thị / お名前",
      email: "Email",
      phone: "Số điện thoại",
      address: "Địa chỉ tại Hà Nội / 住所",
      addressPlaceholder: "VD: Hoàn Kiếm, Hà Nội",
      saveBtn: "Lưu thay đổi",
      saved: "Đã lưu thành công!",
      passwordTitle: "Đổi mật khẩu",
      currentPassword: "Mật khẩu hiện tại",
      newPassword: "Mật khẩu mới",
      newPasswordPlaceholder: "Ít nhất 6 ký tự",
      confirmPassword: "Xác nhận mật khẩu mới",
      confirmPlaceholder: "Nhập lại mật khẩu",
      changePasswordBtn: "Đổi mật khẩu",
      storeManagement: "Quản lý quán",
      ownerRole: "Chủ nhà hàng 🏪",
      dinerRole: "Tìm quán ăn 🍜",
      passwordMismatch: "Mật khẩu mới không khớp",
    },
    // Write Review
    review: {
      back: "Quay lại",
      title: "Viết đánh giá",
      ratingTitle: "Đánh giá tổng thể",
      ratingDesc: "Hãy cho điểm nhà hàng này từ 1 đến 5 sao",
      commentTitle: "Nhận xét",
      commentJpNote: "Vui lòng viết nhận xét bằng tiếng Nhật",
      commentPlaceholder: "VD: Súp rất đậm đà, nhân viên thân thiện và phục vụ tốt. Chắc chắn sẽ quay lại!",
      imageTitle: "Thêm ảnh (tùy chọn)",
      imageDesc: "Chỉ nhận jpg, jpeg, png, webp. Mỗi ảnh tối đa 10MB, tối đa 3 ảnh",
      addImage: "Thêm",
      tipsTitle: "💡 Mẹo viết đánh giá hay",
      tips: [
        "Mô tả cụ thể về hương vị và ngoại hình món ăn",
        "Đề cập đến khả năng tiếng Nhật của nhân viên",
        "Đánh giá tỷ lệ giá/chất lượng",
        "Cho biết liệu món ăn có phù hợp khẩu vị Nhật không",
      ],
      submitBtn: "Đăng đánh giá",
      submitting: "Đang đăng...",
      successTitle: "Đã đăng đánh giá!",
      successDesc: "Cảm ơn bạn. Đang quay lại trang nhà hàng...",
      loginRequired: "Bạn cần đăng nhập để viết đánh giá",
      notFound: "Không tìm thấy nhà hàng",
      backToSearch: "Quay lại tìm kiếm",
      ratingLabels: ["", "Rất không hài lòng", "Không hài lòng", "Bình thường", "Hài lòng", "Rất hài lòng!"],
      errorRating: "Vui lòng chọn đánh giá",
      errorComment: "Vui lòng nhập nhận xét",
      errorCommentLength: "Nhận xét phải có ít nhất 20 ký tự",
      errorImageSize: "Mỗi ảnh phải nhỏ hơn hoặc bằng 10MB",
      errorImageType: "Chỉ cho phép ảnh jpg, jpeg, png hoặc webp",
      errorImageCount: "Chỉ được upload tối đa 3 ảnh",
      submitError: "Không thể đăng đánh giá. Vui lòng thử lại",
    },
    // Register Store
    registerStore: {
      back: "Quay lại",
      title: "Đăng ký quán mới",
      pageTitle: "Đăng ký thông tin quán",
      pageSub: "Đăng ký thông tin quán ăn của bạn",
      step1: "Thông tin cơ bản",
      step2: "Thực đơn",
      step3: "Ảnh & Thẻ",
      nameVn: "Tên quán (Tiếng Việt)",
      errNameVn: "Vui lòng nhập tên quán (Tiếng Việt)",
      nameJp: "Tên quán (Tiếng Nhật)",
      errNameJp: "Vui lòng nhập tên quán (Tiếng Nhật)",
      address: "Địa chỉ / 住所",
      errAddress: "Vui lòng nhập địa chỉ",
      errRequired: "Vui lòng nhập đầy đủ các trường bắt buộc",
      selectMap: "Chọn từ bản đồ",
      phone: "Số điện thoại",
      errPhone: "Vui lòng nhập số điện thoại",
      openHours: "Giờ mở cửa",
      errOpenHours: "Vui lòng nhập giờ mở cửa",
      avgPrice: "Giá trung bình (VND)",
      errAvgPrice: "Vui lòng nhập giá trung bình",
      descVn: "Mô tả (Tiếng Việt)",
      errDescVn: "Vui lòng nhập mô tả (Tiếng Việt)",
      descVnPh: "Mô tả quán bằng tiếng Việt...",
      descJp: "Mô tả (Tiếng Nhật)",
      errDescJp: "Vui lòng nhập mô tả (Tiếng Nhật)",
      descJpPh: "Mô tả quán bằng tiếng Nhật...",
      nextStep2: "Tiếp theo: Thiết lập thực đơn",
      menuTitle: "Thiết lập thực đơn",
      addBtn: "Thêm",
      menuLabel: "Món",
      errMenuRequired: "Vui lòng thêm ít nhất một món ăn",
      dishImage: "Ảnh món",
      addDishImage: "Thêm ảnh món",
      errDishImage: "Vui lòng thêm ảnh món ăn",
      dishNameVn: "Tên món (Tiếng Việt)",
      errDishNameVn: "Vui lòng nhập tên món tiếng Việt",
      dishNameJp: "Tên món (Tiếng Nhật)",
      errDishNameJp: "Vui lòng nhập tên món tiếng Nhật",
      price: "Giá (VND)",
      errDishPrice: "Vui lòng nhập giá lớn hơn 0",
      dishDesc: "Mô tả (tùy chọn)",
      errDishDesc: "Vui lòng nhập mô tả món ăn",
      prevBtn: "Quay lại",
      nextStep3: "Tiếp theo: Ảnh & Thẻ",
      photoTitle: "Ảnh quán & Món ăn",
      photoSub: "Tải lên tối đa 8 ảnh",
      addPhoto: "Thêm ảnh",
      errImages: "Vui lòng thêm ít nhất một ảnh quán",
      errorImageCount: "Chỉ được upload tối đa 8 ảnh",
      errorImageSize: "Mỗi ảnh phải nhỏ hơn hoặc bằng 10MB",
      errorImageType: "Chỉ cho phép ảnh jpg, jpeg, png hoặc webp",
      tagTitle: "Thẻ món ăn",
      tagSub: "Chọn các thẻ phù hợp với quán của bạn",
      errTags: "Vui lòng chọn ít nhất một thẻ món ăn",
      submitBtn: "Đăng ký quán",
      saving: "Đang lưu...",
      successTitle: "Đăng ký quán thành công!",
      successSub: "Đang quay lại trang quản lý quán...",
      errSubmit: "Không thể lưu thông tin quán. Vui lòng thử lại.",
    },
    // Owner List
    ownerList: {
      title: "Danh sách quán của tôi",
      titleSub: "私の店舗一覧",
      addBtn: "Đăng ký mới",
      addBtnMobile: "Thêm",
      statStores: "Quán đã đăng ký",
      statReviews: "Tổng đánh giá",
      statRating: "Đánh giá TB",
      open: "Đang mở",
      closed: "Đã đóng",
      reviewsCount: "đánh giá",
      edit: "Chỉnh sửa",
      publicPage: "Trang công khai",
      messages: "Tin nhắn",
      emptyTitle: "Chưa có quán nào",
      emptyDesc: "Đăng ký quán đầu tiên để khách Nhật có thể tìm thấy bạn!",
      emptyBtn: "Đăng ký quán đầu tiên",
      addNew: "Đăng ký quán mới",
    },
    // Manage Store
    manageStore: {
      back: "Quay lại",
      publicPage: "Trang công khai →",
      notFound: "Không tìm thấy quán",
      open: "Đang mở",
      closed: "Đã đóng",
      saved: "Đã lưu thay đổi!",
      tabs: {
        basic: "Thông tin cơ bản",
        menu: "Thực đơn",
        photos: "Ảnh & Thẻ",
      },
      nameVn: "Tên quán (Tiếng Việt)",
      nameJp: "Tên quán (Tiếng Nhật)",
      address: "Địa chỉ",
      phone: "Số điện thoại",
      openHours: "Giờ mở cửa",
      avgPrice: "Giá trung bình (VND)",
      descVn: "Mô tả (Tiếng Việt)",
      descJp: "Mô tả (Tiếng Nhật)",
      saveChanges: "Lưu thay đổi",
      menuTitle: "Quản lý thực đơn",
      add: "Thêm",
      dishImage: "Ảnh món",
      addDishImage: "Thêm ảnh món",
      changePhoto: "Đổi ảnh",
      dishNameVn: "Tên món (Tiếng Việt)",
      dishNameJp: "Tên món (Tiếng Nhật)",
      price: "Giá",
      description: "Mô tả",
      saveMenu: "Lưu thực đơn",
      photoTitle: "Quản lý ảnh",
      addPhoto: "Thêm ảnh",
      tagTitle: "Thẻ món ăn",
      savePhotos: "Lưu thay đổi",
      errorImageCount: "Chỉ được upload tối đa 8 ảnh",
      errorImageSize: "Mỗi ảnh phải nhỏ hơn hoặc bằng 10MB",
      errorImageType: "Chỉ cho phép ảnh jpg, jpeg, png hoặc webp",
      submitError: "Không thể lưu thay đổi. Vui lòng thử lại.",
    },
    // Restaurant Card
    card: {
      open: "Đang mở",
      closed: "Đã đóng",
      reviews: "đánh giá",
      from: "từ ",
    },
  },
} as const;

type Translations = typeof translations;
type LangTranslations = Translations["ja"];

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: LangTranslations;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ja");

  const t = translations[language] as LangTranslations;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
}
